CREATE TABLE IF NOT EXISTS DRIVE_TABLE (
    -- Core Pipeline Identity
    WHO_RAN_PIPELINE VARCHAR(100) DEFAULT NULL,
    PIPELINE_NAME VARCHAR(500) DEFAULT NULL,
    PIPELINE_PRIORITY FLOAT DEFAULT NULL,
    DAG_RUN_ID VARCHAR(200) DEFAULT NULL,
    PIPELINE_PARALLEL_THREAD_ID VARCHAR(200) DEFAULT NULL,
    
    -- Data Flow Locations
    SOURCE_NAME VARCHAR(300) DEFAULT NULL,
    STAGE_NAME VARCHAR(300) DEFAULT NULL,
    TARGET_NAME VARCHAR(300) DEFAULT NULL,
    
    -- Data Extraction Parameters
    QUERY_TARGET_DAY VARCHAR(50) DEFAULT NULL,
    QUERY_WINDOW_START_TIME VARCHAR(50) DEFAULT NULL,
    QUERY_WINDOW_END_TIME VARCHAR(50) DEFAULT NULL,
    TIME_INTERVAL VARCHAR(50) DEFAULT NULL,
    
    -- Record Audit Timestamps
    RECORD_FIRST_INSERTED_TIME VARCHAR(50) DEFAULT NULL,
    RECORD_LAST_UPDATE_TIME VARCHAR(50) DEFAULT NULL,
    
    -- Component Classification
    SOURCE_CATEGORY VARCHAR(300) DEFAULT NULL,
    SOURCE_SUB_TYPE VARCHAR(300) DEFAULT NULL,
    STAGE_CATEGORY VARCHAR(300) DEFAULT NULL,
    STAGE_SUB_TYPE VARCHAR(300) DEFAULT NULL,
    TARGET_CATEGORY VARCHAR(500) DEFAULT NULL,
    TARGET_SUB_TYPE VARCHAR(300) DEFAULT NULL,
    
    -- Hash-based Identifiers
    SOURCE_ID VARCHAR(100) DEFAULT NULL,
    STAGE_ID VARCHAR(100) DEFAULT NULL,
    TARGET_ID VARCHAR(100) DEFAULT NULL,
    PIPELINE_ID VARCHAR(100) DEFAULT NULL,
    
    -- Source to Stage Transfer Process
    SRC_STG_XFER_ENABLED BOOLEAN DEFAULT NULL,
    SRC_STG_XFER_STATUS VARCHAR(50) DEFAULT 'PENDING',
    SRC_STG_XFER_START_TS VARCHAR(50) DEFAULT NULL,
    SRC_STG_XFER_END_TS VARCHAR(50) DEFAULT NULL,
    SRC_STG_XFER_DURATION VARCHAR(50) DEFAULT NULL,
    SRC_STG_XFER_EXP_DURATION VARCHAR(50) DEFAULT NULL,
    
    -- Stage to Target Transfer Process
    STG_TGT_XFER_ENABLED BOOLEAN DEFAULT NULL,
    STG_TGT_XFER_STATUS VARCHAR(50) DEFAULT 'PENDING',
    STG_TGT_XFER_START_TS VARCHAR(50) DEFAULT NULL,
    STG_TGT_XFER_END_TS VARCHAR(50) DEFAULT NULL,
    STG_TGT_XFER_DURATION VARCHAR(50) DEFAULT NULL,
    STG_TGT_XFER_EXP_DURATION VARCHAR(50) DEFAULT NULL,
    
    -- Source to Stage Audit Process
    SRC_STG_AUDIT_ENABLED BOOLEAN DEFAULT NULL,
    SRC_STG_AUDIT_STATUS VARCHAR(50) DEFAULT 'PENDING',
    SRC_STG_AUDIT_START_TS VARCHAR(50) DEFAULT NULL,
    SRC_STG_AUDIT_END_TS VARCHAR(50) DEFAULT NULL,
    SRC_STG_AUDIT_DURATION VARCHAR(50) DEFAULT NULL,
    SRC_STG_AUDIT_EXP_DURATION VARCHAR(50) DEFAULT NULL,
    
    -- Stage to Target Audit Process
    STG_TGT_AUDIT_ENABLED BOOLEAN DEFAULT NULL,
    STG_TGT_AUDIT_STATUS VARCHAR(50) DEFAULT 'PENDING',
    STG_TGT_AUDIT_START_TS VARCHAR(50) DEFAULT NULL,
    STG_TGT_AUDIT_END_TS VARCHAR(50) DEFAULT NULL,
    STG_TGT_AUDIT_DURATION VARCHAR(50) DEFAULT NULL,
    STG_TGT_AUDIT_EXP_DURATION VARCHAR(50) DEFAULT NULL,
    
    -- Data Quality & Validation
    SOURCE_COUNT BIGINT DEFAULT NULL,
    AVG_SOURCE_COUNT BIGINT DEFAULT NULL,
    STAGE_COUNT BIGINT DEFAULT NULL,
    TARGET_COUNT BIGINT DEFAULT NULL,
    AUDIT_RESULT VARCHAR(50) DEFAULT NULL,
    CAN_FETCH_HISTORICAL_DATA BOOLEAN DEFAULT NULL,
    CONTINUITY_CHECK_PERFORMED BOOLEAN DEFAULT NULL,
    PARALLELIZATION_ENABLED BOOLEAN DEFAULT NULL,
    
    -- Pipeline Execution Tracking
    PHASE_COMPLETED VARCHAR(100) DEFAULT NULL,
    PIPELINE_STATUS VARCHAR(50) DEFAULT NULL,
    PIPELINE_START_TIME VARCHAR(50) DEFAULT NULL,
    PIPELINE_END_TIME VARCHAR(50) DEFAULT NULL,
    PIPELINE_DURATION VARCHAR(50) DEFAULT NULL,
    PIPELINE_EXP_DURATION VARCHAR(50) DEFAULT NULL,
    RETRY_ATTEMPT_NUMBER INTEGER DEFAULT NULL,
    
    -- Alerting & Miscellaneous
    EMAIL_ALERTS_SEND_TO VARCHAR(1000) DEFAULT NULL,
    MISCELLANEOUS_DATA VARIANT DEFAULT NULL
);